version: '3.8'
services:
  postgres_practice:
    image: postgres:10.5
    container_name: postgres_practice
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    hostname: postgres
    restart: always
    user: root